# Generated by Django 4.1.1 on 2022-10-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=120)),
                ('product_name', models.CharField(max_length=120)),
                ('product_price', models.CharField(max_length=120)),
            ],
        ),
    ]
