# Generated by Django 4.1.1 on 2022-10-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_alter_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
