# Generated by Django 4.1.2 on 2022-11-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0011_product_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='List',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[], default=' ', max_length=32),
        ),
    ]
