# Generated by Django 4.1.2 on 2022-11-14 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0014_product_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='temp',
        ),
    ]
