# Generated by Django 4.1.2 on 2022-11-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0015_remove_product_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='foo',
            field=models.CharField(default='', max_length=200),
        ),
    ]
