# Generated by Django 4.1.1 on 2022-10-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_product_product_img_user_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.CharField(default='', max_length=450),
        ),
    ]
