# Generated by Django 4.1.2 on 2022-11-14 10:26

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0010_alter_otp_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='List',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), default=' ', max_length=66, size=6),
        ),
    ]
