# Generated by Django 4.1.1 on 2022-10-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='option',
        ),
        migrations.AddField(
            model_name='answer',
            name='opt_1',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='answer',
            name='opt_2',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='answer',
            name='opt_3',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='answer',
            name='opt_4',
            field=models.CharField(default='', max_length=120),
        ),
    ]
