# Generated by Django 4.1.1 on 2022-10-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_answer_option_answer_opt_1_answer_opt_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='opt_1',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='opt_2',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='opt_3',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='opt_4',
        ),
        migrations.AddField(
            model_name='quiz',
            name='opt_1',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='quiz',
            name='opt_2',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='quiz',
            name='opt_3',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='quiz',
            name='opt_4',
            field=models.CharField(default='', max_length=120),
        ),
    ]
