# Generated by Django 4.1.2 on 2022-10-20 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0009_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='description',
            new_name='order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.AddField(
            model_name='order',
            name='buy_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 20, 8, 47, 5, 666282)),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_satuts',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='user_info',
        ),
    ]
