# Generated by Django 4.1.2 on 2022-10-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_alter_user_info_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='order_id',
            field=models.CharField(default=' ', max_length=120),
        ),
        migrations.AddField(
            model_name='user_info',
            name='payment_id',
            field=models.CharField(default=' ', max_length=120),
        ),
    ]
