# Generated by Django 4.1.2 on 2022-10-21 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0011_alter_order_amount_alter_order_buy_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
    ]
