# Generated by Django 4.1.1 on 2022-10-11 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=128)),
                ('option_1', models.CharField(default='', max_length=120)),
                ('option_2', models.CharField(default='', max_length=120)),
                ('option_3', models.CharField(default='', max_length=120)),
                ('option_4', models.CharField(default='', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Score_Calculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField(default=0)),
                ('marks_user', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_time', models.DateTimeField()),
                ('score', models.CharField(max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_answer', models.CharField(max_length=120)),
                ('question_time', models.CharField(max_length=120)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.quiz_model')),
            ],
        ),
    ]
