# Generated by Django 4.1.2 on 2022-10-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0009_user_info_order_id_user_info_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='order_id',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='payment_id',
            field=models.CharField(max_length=120),
        ),
    ]
